/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8a3ae39f-1c00-41e7-8805-24add6e16584",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ltr44JEKo",
    "aws_user_pools_web_client_id": "4ooei9ujavlh6vagagvb2ss5ga",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://eyda3kamcfclhhmsyvsyf4hoai.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r5azk4ca7fcshbm26zrjejlipu",
    "aws_user_files_s3_bucket": "rspreact48fa851a4524a484cb06ce6a8dfcbcfcc64219-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
